package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.85

import (
	"context"
	"fmt"

	"github.com/jinzhu/copier"
	"github.com/tuken/nix/db"
	"github.com/tuken/nix/graph/model"
	"github.com/tuken/nix/pipeline"
)

// CreateField is the resolver for the createField field.
func (r *mutationResolver) CreateField(ctx context.Context, input model.CreateFieldInput) (*model.Field, error) {
	return createField(ctx, pipeline.MustUser(ctx), input)
}

// CreateFieldWithUserID is the resolver for the createFieldWithUserID field.
func (r *mutationResolver) CreateFieldWithUserID(ctx context.Context, userID int, input model.CreateFieldInput) (*model.Field, error) {
	d := pipeline.MustDB(ctx)

	user := db.User{}
	if err := d.Preload("Org").Preload("Parent").Preload("Role").Preload("Fields").First(&user, userID).Error; err != nil {
		return nil, fmt.Errorf("ユーザーが見つかりませんでした。user_id: %d", userID)
	}

	return createField(ctx, &user, input)
}

// FieldTypes is the resolver for the fieldTypes field.
func (r *queryResolver) FieldTypes(ctx context.Context) ([]*model.FieldType, error) {
	d := pipeline.MustDB(ctx)

	dbFT := []*db.FieldType{}
	if err := d.Find(&dbFT).Error; err != nil {
		return nil, err
	}

	fields := []*model.FieldType{}
	copier.Copy(&fields, &dbFT)

	return fields, nil
}

// GetField is the resolver for the getField field.
func (r *queryResolver) GetField(ctx context.Context, id int) (*model.Field, error) {
	return getField(ctx, pipeline.MustUser(ctx), id)
}

// GetFieldByUserID is the resolver for the getFieldByUserID field.
func (r *queryResolver) GetFieldByUserID(ctx context.Context, userID int, id int) (*model.Field, error) {
	d := pipeline.MustDB(ctx)

	user := db.User{}
	if err := d.Preload("Org").Preload("Parent").Preload("Role").Preload("Fields").First(&user, userID).Error; err != nil {
		return nil, fmt.Errorf("ユーザーが見つかりませんでした。user_id: %d", userID)
	}

	return getField(ctx, &user, id)
}

// ListFields is the resolver for the listFields field.
func (r *queryResolver) ListFields(ctx context.Context) ([]*model.Field, error) {
	return listFields(ctx, pipeline.MustUser(ctx))
}

// ListFieldsWithUserID is the resolver for the listFieldsWithUserID field.
func (r *queryResolver) ListFieldsWithUserID(ctx context.Context, userID int) ([]*model.Field, error) {
	d := pipeline.MustDB(ctx)

	user := db.User{}
	if err := d.Preload("Org").Preload("Parent").Preload("Role").Preload("Fields").First(&user, userID).Error; err != nil {
		return nil, fmt.Errorf("ユーザーが見つかりませんでした。user_id: %d", userID)
	}

	return listFields(ctx, &user)
}
