package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.85

import (
	"context"
	"fmt"

	"github.com/jinzhu/copier"
	"github.com/tuken/nix/db"
	"github.com/tuken/nix/graph/model"
	"github.com/tuken/nix/middleware"
)

// CreateField is the resolver for the createField field.
func (r *mutationResolver) CreateField(ctx context.Context, input model.NewField) (*model.Field, error) {
	d := middleware.MustDB(ctx)

	newField := &db.Field{
		UserID:      uint(input.UserID),
		Name:        input.Name,
		Latitude:    input.Latitude,
		Longitude:   input.Longitude,
		Boundary:    db.Polygon{WKT: input.Boundary},
		PostalCode:  input.PostalCode,
		Address:     input.Address,
		FieldTypeID: uint(input.FieldTypeID),
		Note:        input.Note,
	}

	if input.FieldCode != nil {
		newField.FieldCode.Scan(*input.FieldCode)
	}

	if input.Elevation != nil {
		newField.Elevation.Scan(*input.Elevation)
	}

	if input.Area != nil {
		newField.Area.Scan(*input.Area)
	}

	if err := d.Create(newField).Error; err != nil {
		return nil, err
	}

	field := &model.Field{}
	copier.Copy(field, newField)

	return field, nil
}

// Fields is the resolver for the fields field.
func (r *queryResolver) Fields(ctx context.Context) ([]*model.Field, error) {
	d := middleware.MustDB(ctx)

	var fields []*model.Field
	if err := d.Find(&fields).Error; err != nil {
		return nil, err
	}

	return fields, nil
}

// Field is the resolver for the field field.
func (r *queryResolver) Field(ctx context.Context, id int) (*model.Field, error) {
	panic(fmt.Errorf("not implemented: Field - field"))
}
