type FieldType {
  id: ID!
  name: String!
  sortOrder: Int!
}

type FieldState {
  id: ID!
  name: String!
  description: String!
}

type Field {
  id: ID!
  user: User!
  fieldType: FieldType!
  fieldCode: String
  name: String!
  latitude: Float!
  longitude: Float!
  elevation: Float
  area: Float
  fieldState: FieldState!
  postalCode: String!
  address: String!
  note: String!
  users: [User!]
}

input CreateFieldInput {
  userID: ID!
  fieldTypeID: ID!
  fieldCode: String
  name: String!
  latitude: Float!
  longitude: Float!
  elevation: Float
  area: Float
  fieldStateID: ID!
  postalCode: String!
  address: String!
  note: String!
}

input UpdateFieldInput {
  userID: ID
  fieldTypeID: ID
  fieldCode: String
  name: String
  latitude: Float
  longitude: Float
  elevation: Float
  area: Float
  fieldStateID: ID
  postalCode: String
  address: String
  note: String
}

extend type Query {
  fieldTypes: [FieldType!]!
  fieldStates: [FieldState!]!
  getField(id: ID!): Field
  listFields: [Field!]!
  findFields(ownerID: ID, fieldID: ID, fieldTypeID: ID, fieldStateID: ID): [Field!]!
}

extend type Mutation {
  createField(input: CreateFieldInput!): Field!
  updateField(id: ID!, input: UpdateFieldInput!): Field!
}
