package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.85

import (
	"context"

	"github.com/jinzhu/copier"
	"github.com/tuken/nix/db"
	"github.com/tuken/nix/graph/model"
	"github.com/tuken/nix/pipeline"
)

// CreateField is the resolver for the createField field.
func (r *mutationResolver) CreateField(ctx context.Context, input model.CreateFieldInput) (*model.Field, error) {
	d := pipeline.MustDB(ctx)

	newField := &db.Field{
		UserID:      uint(input.UserID),
		Name:        input.Name,
		Latitude:    input.Latitude,
		Longitude:   input.Longitude,
		Boundary:    db.Polygon{WKT: input.Boundary},
		PostalCode:  input.PostalCode,
		Address:     input.Address,
		FieldTypeID: uint(input.FieldTypeID),
		Note:        input.Note,
	}

	if input.FieldCode != nil {
		newField.FieldCode.Scan(*input.FieldCode)
	}

	if input.Elevation != nil {
		newField.Elevation.Scan(*input.Elevation)
	}

	if input.Area != nil {
		newField.Area.Scan(*input.Area)
	}

	if err := d.Create(newField).Error; err != nil {
		return nil, err
	}

	field := &model.Field{}
	copier.Copy(field, newField)

	return field, nil
}

// FieldTypes is the resolver for the fieldTypes field.
func (r *queryResolver) FieldTypes(ctx context.Context) ([]*model.FieldType, error) {
	d := pipeline.MustDB(ctx)

	dbFT := []*db.FieldType{}
	if err := d.Find(&dbFT).Error; err != nil {
		return nil, err
	}

	fields := []*model.FieldType{}
	copier.Copy(&fields, &dbFT)

	return fields, nil
}

// FindFieldsByUser is the resolver for the findFieldsByUser field.
func (r *queryResolver) FindFieldsByUser(ctx context.Context, userID int) ([]*model.Field, error) {
	d := pipeline.MustDB(ctx)

	dbField := []db.Field{}
	if err := d.Preload("Org").Preload("User").Preload("FieldType").Find(&dbField, "user_id = ?", userID).Error; err != nil {
		return nil, err
	}

	fields := []*model.Field{}
	copier.Copy(&fields, &dbField)

	return fields, nil
}

// GetField is the resolver for the getField field.
func (r *queryResolver) GetField(ctx context.Context, id int) (*model.Field, error) {
	d := pipeline.MustDB(ctx)

	dbField := db.Field{}
	if err := d.Preload("Org").Preload("User").Preload("FieldType").Last(&dbField, id).Error; err != nil {
		return nil, err
	}

	field := model.Field{}
	copier.Copy(&field, &dbField)

	return &field, nil
}
