type FieldType {
  id: ID!
  name: String!
  sortOrder: Int!
}

type Field {
  id: ID!
  user: User!
  fieldType: FieldType!
  fieldCode: String
  name: String!
  latitude: Float!
  longitude: Float!
  elevation: Float
  area: Float
  postalCode: String!
  address: String!
  status: String!
  note: String!
  users: [User!]
}

input CreateFieldInput {
  userID: Int!
  fieldTypeID: Int!
  fieldCode: String
  name: String!
  latitude: Float!
  longitude: Float!
  elevation: Float
  area: Float
  postalCode: String!
  address: String!
  note: String!
}

extend type Query {
  fieldTypes: [FieldType!]!
  findFieldsByUser(userId: Int!): [Field!]!
  getField(id: ID!): Field!
}

extend type Mutation {
  createField(input: CreateFieldInput!): Field!
}
