package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.85

import (
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"net/http"

	"github.com/jinzhu/copier"
	"github.com/tuken/nix/conf"
	"github.com/tuken/nix/db"
	"github.com/tuken/nix/graph/model"
	"github.com/tuken/nix/pipeline"
)

// CreateOrg is the resolver for the createOrg field.
func (r *mutationResolver) CreateOrg(ctx context.Context, input model.CreateOrgInput) (*model.Org, error) {
	d := pipeline.MustDB(ctx)

	newOrg := &db.Org{
		Name:       input.Name,
		PostalCode: input.PostalCode,
		Address:    input.Address,
		Note:       input.Note,
	}

	if err := d.Create(newOrg).Error; err != nil {
		return nil, err
	}

	org := model.Org{}
	copier.Copy(&org, newOrg)

	return &org, nil
}

// Orgs is the resolver for the orgs field.
func (r *queryResolver) Orgs(ctx context.Context) ([]*model.Org, error) {
	d := pipeline.MustDB(ctx)

	dbOrgs := []db.Org{}
	if err := d.Find(&dbOrgs).Error; err != nil {
		return nil, err
	}

	orgs := []*model.Org{}
	copier.Copy(&orgs, &dbOrgs)

	return orgs, nil
}

// Roles is the resolver for the roles field.
func (r *queryResolver) Roles(ctx context.Context) ([]*model.Role, error) {
	d := pipeline.MustDB(ctx)

	dbRoles := []db.Role{}
	if err := d.Find(&dbRoles).Error; err != nil {
		return nil, err
	}

	roles := []*model.Role{}
	copier.Copy(&roles, &dbRoles)

	return roles, nil
}

// CropItems is the resolver for the cropItems field.
func (r *queryResolver) CropItems(ctx context.Context) ([]*model.CropItem, error) {
	d := pipeline.MustDB(ctx)

	dbItems := []db.CropItem{}
	if err := d.Find(&dbItems).Error; err != nil {
		return nil, err
	}

	items := []*model.CropItem{}
	copier.Copy(&items, &dbItems)

	return items, nil
}

// CropVarieties is the resolver for the cropVarieties field.
func (r *queryResolver) CropVarieties(ctx context.Context, itemID int) ([]*model.CropVariety, error) {
	d := pipeline.MustDB(ctx)

	dbVarieties := []db.CropVariety{}
	if err := d.Preload("CropItem").Where("crop_item_id = ?", itemID).Find(&dbVarieties).Error; err != nil {
		return nil, err
	}

	varieties := []*model.CropVariety{}
	copier.Copy(&varieties, &dbVarieties)

	return varieties, nil
}

// Weathers is the resolver for the weathers field.
func (r *queryResolver) Weathers(ctx context.Context) ([]*model.Weather, error) {
	d := pipeline.MustDB(ctx)

	dbWeathers := []db.Weather{}
	if err := d.Find(&dbWeathers).Error; err != nil {
		return nil, err
	}

	weathers := []*model.Weather{}
	copier.Copy(&weathers, &dbWeathers)

	return weathers, nil
}

// Forecasts is the resolver for the forecasts field.
func (r *queryResolver) Forecasts(ctx context.Context, latitude float64, longitude float64, days int) ([]*model.Forecast, error) {
	if days < 1 || days > 16 {
		return nil, errors.New("daysは1〜16の範囲で指定してください")
	}

	url := fmt.Sprintf(
		"%s?latitude=%f&longitude=%f&timezone=Asia%%2FTokyo&daily=temperature_2m_max,temperature_2m_min,precipitation_sum,weathercode&forecast_days=%d",
		conf.OpenMeteoURL,
		latitude,
		longitude,
		days,
	)

	res, err := http.Get(url)
	if err != nil {
		return nil, err
	}

	defer func() {
		res.Body.Close()
	}()

	resBody, err := io.ReadAll(res.Body)
	if err != nil {
		return nil, err
	}

	// ステータスコードチェック
	if res.StatusCode >= http.StatusBadRequest {
		return nil, fmt.Errorf("error http response(%d) (url=%s) (body=%s)", res.StatusCode, url, string(resBody))
	}

	forecast := struct {
		Latitude  float64 `json:"latitude"`
		Longitude float64 `json:"longitude"`
		Timezone  string  `json:"timezone"`
		Daily     struct {
			Time           []string  `json:"time"`
			TemperatureMax []float64 `json:"temperature_2m_max"`
			TemperatureMin []float64 `json:"temperature_2m_min"`
			Precipitation  []float64 `json:"precipitation_sum"`
			WeatherCode    []int     `json:"weathercode"`
		} `json:"daily"`
	}{}
	if err := json.Unmarshal(resBody, &forecast); err != nil {
		return nil, fmt.Errorf("error unmarshal response body (body=%s): %v", string(resBody), err)
	}

	dbWeathers := []db.Weather{}
	if err := pipeline.MustDB(ctx).Find(&dbWeathers).Error; err != nil {
		return nil, err
	}

	weathers := []*model.Weather{}
	copier.Copy(&weathers, &dbWeathers)

	result := make([]*model.Forecast, len(forecast.Daily.Time))
	for i := range forecast.Daily.Time {

		result[i] = &model.Forecast{
			Time:             forecast.Daily.Time[i],
			TemperatureMax:   forecast.Daily.TemperatureMax[i],
			TemperatureMin:   forecast.Daily.TemperatureMin[i],
			PrecipitationSum: forecast.Daily.Precipitation[i],
			Weather: func(code int) *model.Weather {

				for _, w := range weathers {

					if w.Code == code {
						return w
					}
				}

				return nil
			}(forecast.Daily.WeatherCode[i]),
		}
	}

	return result, nil
}

// WorkTypeSummary is the resolver for the workTypeSummary field.
func (r *queryResolver) WorkTypeSummary(ctx context.Context) ([]*model.WorkTypeSummaryItem, error) {
	d := pipeline.MustDB(ctx)
	l := pipeline.MustLogger(ctx)

	sums := []struct {
		WorkTypeID uint
		db.WorkType
		Today     int
		Yesterday int
		ThisWeek  int
		LastWeek  int
		ThisMonth int
	}{}

	if err := d.Model(&db.WorkReport{}).Select("work_reports.work_type_id, wt.*, " + "SUM(CASE WHEN work_date >= CURDATE() AND work_date < CURDATE() + INTERVAL 1 DAY THEN 1 ELSE 0 END) AS today, " + "SUM(CASE WHEN work_date >= CURDATE() - INTERVAL 1 DAY AND work_date < CURDATE() THEN 1 ELSE 0 END) AS yesterday, " + "SUM(CASE WHEN YEARWEEK(work_date, 0) = YEARWEEK(CURDATE(), 0) THEN 1 ELSE 0 END) AS this_week, " + "SUM(CASE WHEN YEARWEEK(work_date, 0) = YEARWEEK(CURDATE() - INTERVAL 7 DAY, 0) THEN 1 ELSE 0 END) AS last_week, " + "SUM(CASE WHEN YEAR(work_date) = YEAR(CURDATE()) AND MONTH(work_date) = MONTH(CURDATE()) THEN 1 ELSE 0 END) AS this_month").Joins("INNER JOIN work_types wt ON wt.id = work_reports.work_type_id").Group("work_reports.work_type_id").Order("work_reports.work_type_id").Find(&sums).Error; err != nil {
		l.Errorw("Error work_reports", "error", err)
		return nil, fmt.Errorf("error work_reports: %v", err)
	}

	items := []*model.WorkTypeSummaryItem{}

	for _, sam := range sums {

		i := model.WorkTypeSummaryItem{}
		copier.Copy(&i.WorkType, &sam.WorkType)
		i.Today = sam.Today
		i.Yesterday = sam.Yesterday
		i.ThisWeek = sam.ThisWeek
		i.LastWeek = sam.LastWeek
		i.ThisMonth = sam.ThisMonth

		items = append(items, &i)
	}

	return items, nil
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
