# GraphQL schema example
#
# https://gqlgen.com/getting-started/

scalar Date
scalar Time
scalar Upload

type Org {
  id: ID!
  name: String!
  postalCode: String!
  address: String!
  latitude: Float!
  longitude: Float!
  note: String!
}

type Role {
  id: ID!
  name: String!
  description: String
}

type CropItem {
  id: ID!
  name: String!
  sortOrder: Int!
}

type CropVariety {
  id: ID!
  cropItem: CropItem!
  name: String!
  sortOrder: Int!
}

type Weather {
  code: Int!
  japanese: String!
}

type Forecast {
  time: String!
  temperatureMax: Float!
  temperatureMin: Float!
  precipitationSum: Float!
  weather: Weather!
}

type WorkTypeSummaryItem {
  workType: WorkType!
  today: Int!
  yesterday: Int!
  thisWeek: Int!
  lastWeek: Int!
  thisMonth: Int!
}

input CreateOrgInput {
  name: String!
  postalCode: String!
  address: String!
  latitude: Float!
  longitude: Float!
  note: String!
}

type Query {
  orgs: [Org!]!
  roles: [Role!]!
  cropItems: [CropItem!]!
  cropVarieties(itemID: ID!): [CropVariety!]!
  weathers: [Weather!]!
  forecasts(latitude: Float!, longitude: Float!, days: Int!): [Forecast!]!
  workTypeSummary: [WorkTypeSummaryItem!]!
}

type Mutation {
  createOrg(input: CreateOrgInput!): Org!
}
