package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.85

import (
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"

	"github.com/jinzhu/copier"
	"github.com/tuken/nix/db"
	"github.com/tuken/nix/graph/model"
	"github.com/tuken/nix/middleware"
)

// CreateOrg is the resolver for the createOrg field.
func (r *mutationResolver) CreateOrg(ctx context.Context, input model.NewOrg) (*model.Org, error) {
	d := middleware.MustDB(ctx)

	newOrg := &model.Org{
		Name:       input.Name,
		PostalCode: input.PostalCode,
		Address:    input.Address,
		Note:       input.Note,
	}

	if err := d.Create(newOrg).Error; err != nil {
		return nil, err
	}

	return newOrg, nil
}

// CreateUser is the resolver for the createUser field.
func (r *mutationResolver) CreateUser(ctx context.Context, input model.NewUser) (*model.User, error) {
	d := middleware.MustDB(ctx)

	newUser := &db.User{
		OrgID:      uint(input.OrgID),
		RoleID:     uint(input.RoleID),
		Email:      input.Email,
		Password:   input.Password,
		Name:       input.Name,
		PostalCode: input.PostalCode,
		Address:    input.Address,
		Birthday:   input.Birthday,
		Note:       input.Note,
	}

	if input.ParentID != nil {
		newUser.ParentID.Scan(*input.ParentID)
	}

	if err := d.Create(newUser).Error; err != nil {
		return nil, err
	}

	dbUser := db.User{}
	if err := d.Preload("Org").Preload("Parent").Preload("Role").First(&dbUser, newUser.ID).Error; err != nil {
		return nil, err
	}

	user := model.User{}
	copier.Copy(&user, &dbUser)

	return &user, nil
}

// CreateField is the resolver for the createField field.
func (r *mutationResolver) CreateField(ctx context.Context, input model.NewField) (*model.Field, error) {
	d := middleware.MustDB(ctx)

	newField := &db.Field{
		OrgID:       uint(input.OrgID),
		UserID:      uint(input.UserID),
		Name:        input.Name,
		Latitude:    input.Latitude,
		Longitude:   input.Longitude,
		Boundary:    db.Polygon{WKT: input.Boundary},
		PostalCode:  input.PostalCode,
		Address:     input.Address,
		FieldTypeID: uint(input.FeildTypeID),
		Note:        input.Note,
	}

	if input.FieldCode != nil {
		newField.FieldCode.Scan(*input.FieldCode)
	}

	if input.Elevation != nil {
		newField.Elevation.Scan(*input.Elevation)
	}

	if input.Area != nil {
		newField.Area.Scan(*input.Area)
	}

	if err := d.Create(newField).Error; err != nil {
		return nil, err
	}

	field := &model.Field{}
	copier.Copy(field, newField)

	return field, nil
}

// Orgs is the resolver for the orgs field.
func (r *queryResolver) Orgs(ctx context.Context) ([]*model.Org, error) {
	d := middleware.MustDB(ctx)

	var orgs []*model.Org
	if err := d.Find(&orgs).Error; err != nil {
		return nil, err
	}

	return orgs, nil
}

// Roles is the resolver for the roles field.
func (r *queryResolver) Roles(ctx context.Context) ([]*model.Role, error) {
	d := middleware.MustDB(ctx)

	var roles []*model.Role
	if err := d.Find(&roles).Error; err != nil {
		return nil, err
	}

	return roles, nil
}

// Users is the resolver for the users field.
func (r *queryResolver) Users(ctx context.Context) ([]*model.User, error) {
	d := middleware.MustDB(ctx)

	dbUser := []db.User{}
	if err := d.Preload("Org").Preload("Parent").Preload("Role").Find(&dbUser).Error; err != nil {
		return nil, err
	}

	user := []*model.User{}
	copier.Copy(&user, &dbUser)

	return user, nil
}

// Fields is the resolver for the fields field.
func (r *queryResolver) Fields(ctx context.Context) ([]*model.Field, error) {
	d := middleware.MustDB(ctx)

	var fields []*model.Field
	if err := d.Find(&fields).Error; err != nil {
		return nil, err
	}

	return fields, nil
}

// Forecasts is the resolver for the forecasts field.
func (r *queryResolver) Forecasts(ctx context.Context, latitude float64, longitude float64) ([]*model.Forecast, error) {
	url := fmt.Sprintf(
		"https://api.open-meteo.com/v1/forecast?latitude=%f&longitude=%f&daily=temperature_2m_max,temperature_2m_min,precipitation_sum,weathercode&timezone=Asia/Tokyo",
		latitude, longitude,
	)

	res, err := http.Get(url)
	if err != nil {
		return nil, err
	}

	defer func() {
		res.Body.Close()
	}()

	resBody, err := io.ReadAll(res.Body)
	if err != nil {
		return nil, err
	}

	// ステータスコードチェック
	if res.StatusCode >= http.StatusBadRequest {
		return nil, fmt.Errorf("error http response(%d) (url=%s) (body=%s)", res.StatusCode, url, string(resBody))
	}

	forecast := struct {
		Latitude  float64 `json:"latitude"`
		Longitude float64 `json:"longitude"`
		Timezone  string  `json:"timezone"`
		Daily     struct {
			Time           []string  `json:"time"`
			TemperatureMax []float64 `json:"temperature_2m_max"`
			TemperatureMin []float64 `json:"temperature_2m_min"`
			Precipitation  []float64 `json:"precipitation_sum"`
			WeatherCode    []int     `json:"weathercode"`
		} `json:"daily"`
	}{}
	if err := json.Unmarshal(resBody, &forecast); err != nil {
		return nil, fmt.Errorf("error unmarshal response body (body=%s): %v", string(resBody), err)
	}

	result := make([]*model.Forecast, len(forecast.Daily.Time))
	for i := range forecast.Daily.Time {

		result[i] = &model.Forecast{
			Time:             forecast.Daily.Time[i],
			TemperatureMax:   forecast.Daily.TemperatureMax[i],
			TemperatureMin:   forecast.Daily.TemperatureMin[i],
			PrecipitationSum: forecast.Daily.Precipitation[i],
			WeatherCode:      forecast.Daily.WeatherCode[i],
		}
	}

	return result, nil
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
