package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.85

import (
	"context"
	"fmt"

	"github.com/jinzhu/copier"
	"github.com/tuken/nix/db"
	"github.com/tuken/nix/graph/model"
	"github.com/tuken/nix/pipeline"
)

// CreateUser is the resolver for the createUser field.
func (r *mutationResolver) CreateUser(ctx context.Context, input model.CreateUserInput) (*model.User, error) {
	return createUser(ctx, pipeline.MustUser(ctx), input)
}

// CreateUserWithUserID is the resolver for the createUserWithUserID field.
func (r *mutationResolver) CreateUserWithUserID(ctx context.Context, userID int, input model.CreateUserInput) (*model.User, error) {
	d := pipeline.MustDB(ctx)

	user := db.User{}
	if err := d.Preload("Org").Preload("Parent").Preload("Role").Preload("Fields").First(&user, userID).Error; err != nil {
		return nil, fmt.Errorf("ユーザーが見つかりませんでした。user_id: %d", userID)
	}

	return createUser(ctx, &user, input)
}

// Users is the resolver for the users field.
func (r *queryResolver) Users(ctx context.Context) ([]*model.User, error) {
	d := pipeline.MustDB(ctx)

	dbUsers := []db.User{}
	if err := d.Preload("Org").Preload("Parent").Preload("Role").Preload("Fields").Find(&dbUsers).Error; err != nil {
		return nil, err
	}

	users := []*model.User{}
	copier.Copy(&users, &dbUsers)

	return users, nil
}

// GetUser is the resolver for the getUser field.
func (r *queryResolver) GetUser(ctx context.Context, id int) (*model.User, error) {
	d := pipeline.MustDB(ctx)

	dbUser := db.User{}
	if err := d.Preload("Org").Preload("Parent").Preload("Role").Preload("Fields").Last(&dbUser, id).Error; err != nil {
		return nil, err
	}

	user := model.User{}
	copier.Copy(&user, &dbUser)

	return &user, nil
}
