type User {
  id: ID!
  org: Org!
  parent: User
  role: Role!
  email: String!
  password: String!
  farmName: String
  firstName: String!
  lastName: String!
  postalCode: String!
  address: String!
  gender: String!
  birthday: Date!
  note: String!
  lastLoginAt: Time
  createdAt: Time!
  fields: [Field!]
}

input CreateUserInput {
  orgID: Int!
  parentID: Int
  roleID: Int!
  email: String!
  password: String!
  farmName: String
  firstName: String!
  lastName: String!
  postalCode: String!
  address: String!
  gender: String!
  birthday: String!
  note: String!
}

extend type Query {
  users: [User!]!
  getUser(id: ID!): User!
}

extend type Mutation {
  createUser(input: CreateUserInput!): User!
}
