package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.85

import (
	"context"
	"fmt"

	"github.com/jinzhu/copier"
	"github.com/tuken/nix/db"
	"github.com/tuken/nix/graph/model"
	"github.com/tuken/nix/middleware"
)

// CreateUser is the resolver for the createUser field.
func (r *mutationResolver) CreateUser(ctx context.Context, input model.CreateUserInput) (*model.User, error) {
	d := middleware.MustDB(ctx)

	newUser := &db.User{
		OrgID:      uint(input.OrgID),
		RoleID:     uint(input.RoleID),
		Email:      input.Email,
		Password:   input.Password,
		Name:       input.Name,
		PostalCode: input.PostalCode,
		Address:    input.Address,
		Birthday:   input.Birthday,
		Note:       input.Note,
	}

	if input.ParentID != nil {
		newUser.ParentID.Scan(*input.ParentID)
	}

	if err := d.Create(newUser).Error; err != nil {
		return nil, err
	}

	dbUser := db.User{}
	if err := d.Preload("Org").Preload("Parent").Preload("Role").First(&dbUser, newUser.ID).Error; err != nil {
		return nil, err
	}

	user := model.User{}
	copier.Copy(&user, &dbUser)

	return &user, nil
}

// Users is the resolver for the users field.
func (r *queryResolver) Users(ctx context.Context) ([]*model.User, error) {
	d := middleware.MustDB(ctx)

	dbUser := []db.User{}
	if err := d.Preload("Org").Preload("Parent").Preload("Role").Find(&dbUser).Error; err != nil {
		return nil, err
	}

	user := []*model.User{}
	copier.Copy(&user, &dbUser)

	return user, nil
}

// GetUser is the resolver for the getUser field.
func (r *queryResolver) GetUser(ctx context.Context, id int) (*model.User, error) {
	panic(fmt.Errorf("not implemented: GetUser - getUser"))
}
