type User {
  id: ID!
  org: Org!
  parent: User
  role: Role!
  email: String!
  password: String!
  farmName: String
  firstName: String!
  lastName: String!
  postalCode: String!
  address: String!
  gender: String!
  birthday: Date!
  note: String!
  lastLoginAt: Time
  createdAt: Time!
  fields: [Field!]
}

input CreateUserInput {
  parentID: Int
  roleID: Int!
  email: String!
  password: String!
  farmName: String
  firstName: String!
  lastName: String!
  postalCode: String!
  address: String!
  gender: String!
  birthday: Date!
  note: String!
}

extend type Query {
  getUser(id: ID!): User
  getUserWithUserID(userID: ID!): User
  listUsers: [User!]!
  listUsersWithUserID(userID: ID!): [User!]!
}

extend type Mutation {
  createUser(input: CreateUserInput!): User!
  createUserWithUserID(userID: ID!, input: CreateUserInput!): User!
}
