package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.85

import (
	"context"

	"github.com/tuken/nix/graph/model"
	"github.com/tuken/nix/pipeline"
)

// CreateUser is the resolver for the createUser field.
func (r *mutationResolver) CreateUser(ctx context.Context, input model.CreateUserInput) (*model.User, error) {
	return createUser(ctx, pipeline.MustUser(ctx), input)
}

// UpdateUser is the resolver for the updateUser field.
func (r *mutationResolver) UpdateUser(ctx context.Context, id int, input model.UpdateUserInput) (*model.User, error) {
	return updateUser(ctx, pipeline.MustUser(ctx), uint(id), input)
}

// DeleteUser is the resolver for the deleteUser field.
func (r *mutationResolver) DeleteUser(ctx context.Context, id int) (*model.User, error) {
	return deleteUser(ctx, pipeline.MustUser(ctx), uint(id))
}

// GetUser is the resolver for the getUser field.
func (r *queryResolver) GetUser(ctx context.Context, id int) (*model.User, error) {
	return getUser(ctx, pipeline.MustUser(ctx), uint(id))
}

// ListUsers is the resolver for the listUsers field.
func (r *queryResolver) ListUsers(ctx context.Context) ([]*model.User, error) {
	return listUsers(ctx, pipeline.MustUser(ctx))
}

// FindUsers is the resolver for the findUsers field.
func (r *queryResolver) FindUsers(ctx context.Context, roleID *int, contains *string) ([]*model.User, error) {
	return findUsers(ctx, pipeline.MustUser(ctx), roleID, contains)
}
