package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.85

import (
	"context"
	"time"

	"github.com/jinzhu/copier"
	"github.com/tuken/nix/db"
	"github.com/tuken/nix/graph/model"
	"github.com/tuken/nix/pipeline"
)

// CreateWorkReport is the resolver for the createWorkReport field.
func (r *mutationResolver) CreateWorkReport(ctx context.Context, input model.CreateWorkReportInput) (*model.WorkReport, error) {
	return createWorkReport(ctx, pipeline.MustUser(ctx), input)
}

// UpdateWorkReport is the resolver for the updateWorkReport field.
func (r *mutationResolver) UpdateWorkReport(ctx context.Context, id int, input model.UpdateWorkReportInput) (*model.WorkReport, error) {
	return updateWorkReport(ctx, pipeline.MustUser(ctx), uint(id), input)
}

// DeleteWorkReport is the resolver for the deleteWorkReport field.
func (r *mutationResolver) DeleteWorkReport(ctx context.Context, id int) (*model.WorkReport, error) {
	return deleteWorkReport(ctx, pipeline.MustUser(ctx), uint(id))
}

// WorkTypes is the resolver for the workTypes field.
func (r *queryResolver) WorkTypes(ctx context.Context) ([]*model.WorkType, error) {
	d := pipeline.MustDB(ctx)

	dbWorkTypes := []*db.WorkType{}
	if err := d.Find(&dbWorkTypes).Error; err != nil {
		return nil, err
	}

	workTypes := []*model.WorkType{}
	copier.Copy(&workTypes, &dbWorkTypes)

	return workTypes, nil
}

// GetWorkReport is the resolver for the getWorkReport field.
func (r *queryResolver) GetWorkReport(ctx context.Context, id int) (*model.WorkReport, error) {
	return getWorkReport(ctx, pipeline.MustUser(ctx), uint(id))
}

// ListWorkReports is the resolver for the listWorkReports field.
func (r *queryResolver) ListWorkReports(ctx context.Context) ([]*model.WorkReport, error) {
	return listWorkReports(ctx, pipeline.MustUser(ctx))
}

// FindWorkReports is the resolver for the findWorkReports field.
func (r *queryResolver) FindWorkReports(ctx context.Context, startDate time.Time, endDate time.Time, ownerID *int, fieldID *int, workTypeID *int) ([]*model.WorkReport, error) {
	return findWorkReports(ctx, pipeline.MustUser(ctx), startDate, endDate, ownerID, fieldID, workTypeID)
}

// LatestWorkReports is the resolver for the latestWorkReports field.
func (r *queryResolver) LatestWorkReports(ctx context.Context, count int) ([]*model.WorkReport, error) {
	return latestWorkReports(ctx, pipeline.MustUser(ctx), count)
}
