package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.85

import (
	"context"
	"fmt"

	"github.com/jinzhu/copier"
	"github.com/tuken/nix/db"
	"github.com/tuken/nix/graph/model"
	"github.com/tuken/nix/middleware"
)

// CreateWorkReport is the resolver for the createWorkReport field.
func (r *mutationResolver) CreateWorkReport(ctx context.Context, input model.CreateWorkReportInput) (*model.WorkReport, error) {
	d := middleware.MustDB(ctx)

	newWorkReport := &db.WorkReport{
		UserID:        uint(input.UserID),
		WorkDate:      input.WorkDate,
		WorkTypeID:    uint(input.WorkTypeID),
		CropVarietyID: uint(input.CropVarietyID),
		WeatherCode:   uint(input.WeatherCode),
	}

	if err := d.Create(newWorkReport).Error; err != nil {
		return nil, err
	}

	workReport := &model.WorkReport{}
	copier.Copy(workReport, newWorkReport)

	return workReport, nil
}

// WorkTypes is the resolver for the workTypes field.
func (r *queryResolver) WorkTypes(ctx context.Context) ([]*model.WorkType, error) {
	d := middleware.MustDB(ctx)

	dbWT := []*db.WorkType{}
	if err := d.Find(&dbWT).Error; err != nil {
		return nil, err
	}

	workTypes := []*model.WorkType{}
	copier.Copy(&workTypes, &dbWT)

	return workTypes, nil
}

// FindWorkReportsByUser is the resolver for the findWorkReportsByUser field.
func (r *queryResolver) FindWorkReportsByUser(ctx context.Context, userID int) ([]*model.WorkReport, error) {
	panic(fmt.Errorf("not implemented: FindWorkReportsByUser - findWorkReportsByUser"))
}

// FindWorkReportsByField is the resolver for the findWorkReportsByField field.
func (r *queryResolver) FindWorkReportsByField(ctx context.Context, fieldID int) ([]*model.WorkReport, error) {
	panic(fmt.Errorf("not implemented: FindWorkReportsByField - findWorkReportsByField"))
}

// GetWorkReport is the resolver for the getWorkReport field.
func (r *queryResolver) GetWorkReport(ctx context.Context, id int) (*model.WorkReport, error) {
	panic(fmt.Errorf("not implemented: GetWorkReport - getWorkReport"))
}
