scalar Date
scalar Upload

type WorkType {
  id: ID!
  name: String!
  sortOrder: Int!
}

type WorkReport {
  id: ID!
  user: User!
  field: Field!
  workDate: Date!
  workType: String!
  cropVariety: CropVariety!
  workHours: Float!
  weather: Weather!
  workDetail: String!
  imageURL: String
}

input CreateWorkReportInput {
  workDate: Date!
  workTypeID: ID!
  fieldID: ID!
  cropVarietyID: ID!
  weatherCode: Int!
  workHours: Float!
  workDetail: String!
  image: Upload
}

extend type Query {
  workTypes: [WorkType!]!
  getWorkReport(id: ID!): WorkReport
  getWorkReportWithUserID(userID: ID!, id: ID!): WorkReport
  listWorkReports: [WorkReport!]!
  listWorkReportsWithUserID(userId: ID!): [WorkReport!]!
  findWorkReports(startDate: Date!, endData: Date!, ownerID: ID, fieldID: ID, workTypeID: ID): [WorkReport!]!
  findWorkReportsWithUserID(userID: ID!, startDate: Date!, endData: Date!, ownerID: ID, fieldID: ID, workTypeID: ID): [WorkReport!]!
}

extend type Mutation {
  createWorkReport(input: CreateWorkReportInput!): WorkReport!
  createWorkReportWithUserID(userID: Int!, input: CreateWorkReportInput!): WorkReport!
}
