package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.85

import (
	"context"

	"github.com/jinzhu/copier"
	"github.com/tuken/nix/db"
	"github.com/tuken/nix/graph/model"
	"github.com/tuken/nix/middleware"
)

// CreateWorkReport is the resolver for the createWorkReport field.
func (r *mutationResolver) CreateWorkReport(ctx context.Context, input model.NewWorkReport) (*model.WorkReport, error) {
	d := middleware.MustDB(ctx)

	newWorkReport := &db.WorkReport{
		UserID:        uint(input.UserID),
		WorkDate:      input.WorkDate,
		WorkTypeID:    uint(input.WorkTypeID),
		CropVarietyID: uint(input.CropVarietyID),
		WeatherCode:   uint(input.WeatherCode),
	}

	if err := d.Create(newWorkReport).Error; err != nil {
		return nil, err
	}

	workReport := &model.WorkReport{}
	copier.Copy(workReport, newWorkReport)

	return workReport, nil
}
