type WorkType {
  id: ID!
  name: String!
  sortOrder: Int!
}

type WorkReport {
  id: ID!
  user: User!
  field: Field!
  workDate: Date!
  workHours: Float!
  workType: WorkType!
  cropVariety: CropVariety!
  weather: Weather!
  workDetail: String!
  imageURL: String
}

input CreateWorkReportInput {
  fieldID: ID!
  workDate: Date!
  workHours: Float!
  workTypeID: ID!
  cropVarietyID: ID!
  weatherCode: Int!
  workDetail: String!
  image: Upload
}

input UpdateWorkReportInput {
  fieldID: ID
  workDate: Date
  workHours: Float
  workTypeID: ID
  cropVarietyID: ID
  weatherCode: Int
  workDetail: String
  image: Upload
}

extend type Query {
  workTypes: [WorkType!]!
  getWorkReport(id: ID!): WorkReport
  getWorkReportWithUserID(userID: ID!, id: ID!): WorkReport
  listWorkReports: [WorkReport!]!
  listWorkReportsWithUserID(userId: ID!): [WorkReport!]!
  findWorkReports(startDate: Date!, endDate: Date!, ownerID: ID, fieldID: ID, workTypeID: ID): [WorkReport!]!
  findWorkReportsWithUserID(userID: ID!, startDate: Date!, endDate: Date!, ownerID: ID, fieldID: ID, workTypeID: ID): [WorkReport!]!
}

extend type Mutation {
  createWorkReport(input: CreateWorkReportInput!): WorkReport!
  createWorkReportWithUserID(userID: Int!, input: CreateWorkReportInput!): WorkReport!
  updateWorkReport(id: ID!, input: UpdateWorkReportInput!): WorkReport!
  updateWorkReportWithUserID(userID: Int!, id: ID!, input: UpdateWorkReportInput!): WorkReport!
}
