package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.85

import (
	"context"
	"fmt"
	"time"

	"github.com/jinzhu/copier"
	"github.com/tuken/nix/db"
	"github.com/tuken/nix/graph/model"
	"github.com/tuken/nix/pipeline"
)

// CreateWorkReport is the resolver for the createWorkReport field.
func (r *mutationResolver) CreateWorkReport(ctx context.Context, input model.CreateWorkReportInput) (*model.WorkReport, error) {
	return createWWorkReport(ctx, pipeline.MustUser(ctx), input)
}

// CreateWorkReportWithUserID is the resolver for the createWorkReportWithUserID field.
func (r *mutationResolver) CreateWorkReportWithUserID(ctx context.Context, userID int, input model.CreateWorkReportInput) (*model.WorkReport, error) {
	d := pipeline.MustDB(ctx)

	user := db.User{}
	if err := d.First(&user, userID).Error; err != nil {
		return nil, fmt.Errorf("ユーザーが見つかりませんでした。user_id: %d", userID)
	}

	return createWWorkReport(ctx, &user, input)
}

// WorkTypes is the resolver for the workTypes field.
func (r *queryResolver) WorkTypes(ctx context.Context) ([]*model.WorkType, error) {
	d := pipeline.MustDB(ctx)

	dbWorkTypes := []*db.WorkType{}
	if err := d.Find(&dbWorkTypes).Error; err != nil {
		return nil, err
	}

	workTypes := []*model.WorkType{}
	copier.Copy(&workTypes, &dbWorkTypes)

	return workTypes, nil
}

// GetWorkReport is the resolver for the getWorkReport field.
func (r *queryResolver) GetWorkReport(ctx context.Context, id int) (*model.WorkReport, error) {
	return getWorkReport(ctx, pipeline.MustUser(ctx), id)
}

// GetWorkReportWithUserID is the resolver for the getWorkReportWithUserID field.
func (r *queryResolver) GetWorkReportWithUserID(ctx context.Context, userID int, id int) (*model.WorkReport, error) {
	d := pipeline.MustDB(ctx)

	user := db.User{}
	if err := d.First(&user, userID).Error; err != nil {
		return nil, fmt.Errorf("ユーザーが見つかりませんでした。user_id: %d", userID)
	}

	return getWorkReport(ctx, &user, id)
}

// ListWorkReports is the resolver for the listWorkReports field.
func (r *queryResolver) ListWorkReports(ctx context.Context) ([]*model.WorkReport, error) {
	return listWorkReports(ctx, pipeline.MustUser(ctx))
}

// ListWorkReportsWithUserID is the resolver for the listWorkReportsWithUserID field.
func (r *queryResolver) ListWorkReportsWithUserID(ctx context.Context, userID int) ([]*model.WorkReport, error) {
	d := pipeline.MustDB(ctx)

	user := db.User{}
	if err := d.First(&user, userID).Error; err != nil {
		return nil, fmt.Errorf("ユーザーが見つかりませんでした。user_id: %d", userID)
	}

	return listWorkReports(ctx, &user)
}

// FindWorkReports is the resolver for the findWorkReports field.
func (r *queryResolver) FindWorkReports(ctx context.Context, startDate time.Time, endData time.Time, ownerID *int, fieldID *int, workTypeID *int) ([]*model.WorkReport, error) {
	return findWorkReports(ctx, pipeline.MustUser(ctx), startDate, endData, ownerID, fieldID, workTypeID)
}

// FindWorkReportsWithUserID is the resolver for the findWorkReportsWithUserID field.
func (r *queryResolver) FindWorkReportsWithUserID(ctx context.Context, userID int, startDate time.Time, endData time.Time, ownerID *int, fieldID *int, workTypeID *int) ([]*model.WorkReport, error) {
	d := pipeline.MustDB(ctx)

	user := db.User{}
	if err := d.First(&user, userID).Error; err != nil {
		return nil, fmt.Errorf("ユーザーが見つかりませんでした。user_id: %d", userID)
	}

	return findWorkReports(ctx, &user, startDate, endData, ownerID, fieldID, workTypeID)
}
