scalar Date
scalar Upload

type WorkType {
  id: ID!
  name: String!
  sortOrder: Int!
}

type WorkReport {
  id: ID!
  user: User!
  field: Field!
  workDate: Date!
  workType: String!
  cropVariety: CropVariety!
  workHours: Float!
  weather: Weather!
  workDetail: String!
  imageURL: String
}

input CreateWorkReportInput {
  workDate: Date!
  workTypeID: ID!
  userID: ID!
  fieldID: ID!
  cropVarietyID: ID!
  weatherCode: Int!
  workHours: Float!
  workDetail: String!
  image: Upload
}

extend type Query {
  workTypes: [WorkType!]!
  findWorkReportsByUser(userId: ID!): [WorkReport!]!
  findWorkReportsByField(fieldId: ID!): [WorkReport!]!
  getWorkReport(id: ID!): WorkReport!
}

extend type Mutation {
  createWorkReport(input: CreateWorkReportInput!): WorkReport!
}
